// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '// HelloWorld': typeof import('./src/components/HelloWorld.vue')['default']
    Cascader: typeof import('./src/components/Cascader/index.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIcons: typeof import('element-plus/es')['ElIcons']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElIoncs: typeof import('element-plus/es')['ElIoncs']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Form: typeof import('./src/components/form/index.vue')['default']
    From: typeof import('./src/components/from/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconCircleClose: typeof import('~icons/ci/rcle-close')['default']
    IconElFold: typeof import('~icons/el/fold')['default']
    IconIcBaseline5g: typeof import('~icons/ic/baseline5g')['default']
    Icons: typeof import('./src/components/icons.vue')['default']
    Iconsss: typeof import('./src/components/iconsss/index.vue')['default']
    ICustomCircleClose: typeof import('~icons/custom/circle-close')['default']
    IMdiAbacus: typeof import('~icons/mdi/abacus')['default']
    Iocn: typeof import('./src/components/icon/index.vue')['default']
    MyPagination: typeof import('./src/components/myPagination/index.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}

export { }
